[package]
name = "nvim-utils-luajit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
once_cell = "1.17.1"

[build-dependencies]
bindgen = "0.64.0"
cc = "1.0.79"
