[package]
name = "nvim-utils-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
mlua = { version = "0.8.7", features = ["luajit", "vendored"] }
proc-macro2 = "1.0.51"
quote = "1.0.23"
syn = { version = "1.0.109", features = ["full"] }
