name: Cargo Build & Test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - name: Setup Nextest
        run:  curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - uses: actions/checkout@v3
      - run:  rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run:  cargo build --verbose
      - run:  cargo nextest run -P ci --verbose --status-level all --all-features