name: LLVM-COV Test Coverage

on:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  llvm-cov:
    name: Run LLVM-COV
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
    - name: Setup Rust
      run:  rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      run:  rustup component add llvm-tools-preview
    - name: Setup LLVM-Cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Setup Nextest
      run:  curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run:  cargo build --verbose
    - name: Run tests
      run:  cargo llvm-cov nextest run -P ci --verbose --status-level all --all-features